// API helper for talking to the Spring Boot backend
import axios from "axios";

// One search result chunk returned by the backend
export interface SearchResult {
  id: number;
  documentTitle: string;
  sectionTitle: string;
  content: string;
  source: string;
  lastUpdated: string;
  sharingStatus: string;
  department: string;
  approved: boolean;
  similarityScore: number | null;
}

// Axios instance with the backend base URL
const api = axios.create({
  baseURL: "http://localhost:8080/api",
});

// Search the knowledge base for the top relevant chunks for a question
export async function searchKnowledgeBase(
  question: string,
): Promise<SearchResult[]> {
  const response = await api.post<SearchResult[]>("/knowledge-base/search", {
    question,
  });
  return response.data;
}

// One ticket returned by the backend
export interface Ticket {
  id: number;
  customerName: string;
  createdBy: string | null;
  assignedTo: string | null;
  status: string;
  urgency: string | null;
  ndaStatus: string | null;
  deadline: string | null;
  businessImpact: string | null;
  eta: string | null;
  createdAt: string | null;
}

// Get all tickets
export async function getTickets(): Promise<Ticket[]> {
  const response = await api.get<Ticket[]>("/tickets");
  return response.data;
}

// One SME request (ETA tracking row) returned by the backend
export interface SmeRequest {
  id: number;
  ticketId: number;
  department: string;
  teamName: string | null;
  questionCount: number | null;
  eta: string | null; // full date-time string, or null if not set yet
  status: string; // Waiting for ETA / ETA Confirmed / Overdue / In Progress / Returned
  confirmedBy: string | null;
  sentAt: string | null;
  returnedAt: string | null;
}

// Get all SME requests for a given ticket (overdue status is computed by the backend)
export async function getSmeRequestsByTicket(
  ticketId: number,
): Promise<SmeRequest[]> {
  const response = await api.get<SmeRequest[]>(
    `/sme-requests/ticket/${ticketId}`,
  );
  return response.data;
}

// One knowledge base chunk returned by the backend
export interface KnowledgeBase {
  id: number;
  documentTitle: string;
  sectionTitle: string;
  content: string;
  source: string;
  lastUpdated: string | null;
  sharingStatus: string; // Public / Customer-shareable / NDA-required
  department: string;
  approved: boolean;
  // note: embedding is generated by the backend and NOT edited here
}

// Payload for creating or updating a chunk (no id, no embedding)
export interface KnowledgeBaseInput {
  documentTitle: string;
  sectionTitle: string;
  content: string;
  source: string;
  lastUpdated: string | null;
  sharingStatus: string;
  department: string;
  approved: boolean;
}

// Get all knowledge base chunks
export async function getKnowledgeBase(): Promise<KnowledgeBase[]> {
  const response = await api.get<KnowledgeBase[]>("/knowledge-base");
  return response.data;
}

// Create a new chunk (backend generates the embedding automatically)
export async function createKnowledge(
  chunk: KnowledgeBaseInput,
): Promise<KnowledgeBase> {
  const response = await api.post<KnowledgeBase>("/knowledge-base", chunk);
  return response.data;
}

// Update an existing chunk (backend regenerates the embedding automatically)
export async function updateKnowledge(
  id: number,
  chunk: KnowledgeBaseInput,
): Promise<KnowledgeBase> {
  const response = await api.put<KnowledgeBase>(`/knowledge-base/${id}`, chunk);
  return response.data;
}

// Delete a chunk
export async function deleteKnowledge(id: number): Promise<void> {
  await api.delete(`/knowledge-base/${id}`);
}
