import { useEffect, useState } from "react";
import {
  BookOpen,
  Plus,
  Search,
  Edit3,
  Trash2,
  Loader2,
  AlertTriangle,
  CheckCircle,
  RefreshCw,
  X,
} from "lucide-react";
import {
  getKnowledgeBase,
  createKnowledge,
  updateKnowledge,
  deleteKnowledge,
  KnowledgeBase,
  KnowledgeBaseInput,
} from "../api";
import { Screen, ToastMsg } from "../types";
import { BtnPrimary, BtnSecondary } from "../components/shared";

// ─── Screen: Knowledge Base Management ────────────────────────────────────────
// CRUD over knowledge entries per KNOWLEDGE_BASE_API_SPEC.md. The embedding is
// generated by the backend and is never shown or sent from here.

const SHARING_OPTIONS = ["Public", "Customer-shareable", "NDA-required"];
const DEPARTMENT_OPTIONS = [
  "InfoSec",
  "Legal",
  "HR",
  "Finance",
  "Treasury",
  "Compliance",
  "ESG",
  "General",
];

const EMPTY_FORM: KnowledgeBaseInput = {
  documentTitle: "",
  sectionTitle: "",
  content: "",
  source: "",
  lastUpdated: null,
  sharingStatus: "Public",
  department: "General",
  approved: false,
};

// Backend sends e.g. "2025-11-03T00:00:00"; show an unambiguous date
function fmtUpdated(raw: string | null): string {
  if (!raw) return "—";
  return `${raw.slice(0, 10)} (UTC)`;
}

function SharingPill({ status }: { status: string }) {
  const map: Record<string, string> = {
    Public: "bg-[#F5F5F5] text-[#374151] border-[rgba(0,0,0,0.1)]",
    "Customer-shareable": "bg-[#FFF4EC] text-[#C05600] border-[#F96702]/25",
    "NDA-required": "bg-[#FEF2F2] text-[#991B1B] border-[#FCA5A5]/50",
  };
  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-[9px] font-bold tracking-[0.08em] uppercase border whitespace-nowrap ${map[status] ?? "bg-[#F5F5F5] text-[#6B7280] border-[rgba(0,0,0,0.1)]"}`}
    >
      {status}
    </span>
  );
}

export function KnowledgeBaseScreen({
  setScreen,
  addToast,
  addLog,
}: {
  setScreen: (s: Screen) => void;
  addToast: (m: string, t?: ToastMsg["type"]) => void;
  addLog: (e: string) => void;
}) {
  const [entries, setEntries] = useState<KnowledgeBase[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [query, setQuery] = useState("");
  // form modal: null = closed, "new" = creating, number = editing that id
  const [formTarget, setFormTarget] = useState<null | "new" | number>(null);
  const [form, setForm] = useState<KnowledgeBaseInput>(EMPTY_FORM);
  const [saving, setSaving] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<KnowledgeBase | null>(null);
  const [deleting, setDeleting] = useState(false);

  const load = () => {
    setLoading(true);
    setError(false);
    getKnowledgeBase()
      .then((data) => setEntries(data))
      .catch((err) => {
        console.error("Failed to load knowledge base:", err);
        setError(true);
      })
      .finally(() => setLoading(false));
  };
  useEffect(load, []);

  const q = query.trim().toLowerCase();
  const visible = q
    ? entries.filter((e) =>
        [e.documentTitle, e.sectionTitle, e.content, e.department]
          .join(" ")
          .toLowerCase()
          .includes(q),
      )
    : entries;

  const openCreate = () => {
    setForm(EMPTY_FORM);
    setFormTarget("new");
  };
  const openEdit = (entry: KnowledgeBase) => {
    setForm({
      documentTitle: entry.documentTitle,
      sectionTitle: entry.sectionTitle,
      content: entry.content,
      source: entry.source,
      lastUpdated: entry.lastUpdated,
      sharingStatus: entry.sharingStatus,
      department: entry.department,
      approved: entry.approved,
    });
    setFormTarget(entry.id);
  };

  const submitForm = async () => {
    if (!form.documentTitle.trim() || !form.sectionTitle.trim() || !form.content.trim()) {
      addToast("Document title, section title and content are required.", "warning");
      return;
    }
    setSaving(true);
    try {
      if (formTarget === "new") {
        await createKnowledge(form);
        addLog(`Knowledge entry created: ${form.documentTitle} / ${form.sectionTitle}`);
        addToast("Knowledge entry created.", "success");
      } else if (typeof formTarget === "number") {
        await updateKnowledge(formTarget, form);
        addLog(`Knowledge entry updated: ${form.documentTitle} / ${form.sectionTitle}`);
        addToast("Knowledge entry updated.", "success");
      }
      setFormTarget(null);
      load();
    } catch (err) {
      console.error("Failed to save knowledge entry:", err);
      addToast("Failed to save knowledge entry.", "warning");
    } finally {
      setSaving(false);
    }
  };

  const confirmDelete = async () => {
    if (!deleteTarget) return;
    setDeleting(true);
    try {
      await deleteKnowledge(deleteTarget.id);
      addLog(`Knowledge entry deleted: ${deleteTarget.documentTitle} / ${deleteTarget.sectionTitle}`);
      addToast("Knowledge entry deleted.", "success");
      setDeleteTarget(null);
      load();
    } catch (err) {
      console.error("Failed to delete knowledge entry:", err);
      addToast("Failed to delete knowledge entry.", "warning");
    } finally {
      setDeleting(false);
    }
  };

  const setField = <K extends keyof KnowledgeBaseInput>(
    key: K,
    value: KnowledgeBaseInput[K],
  ) => setForm((p) => ({ ...p, [key]: value }));

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Header (Dashboard-style: top-level page, no back breadcrumb) */}
      <div className="px-7 pt-6 pb-4 bg-white border-b border-[rgba(0,0,0,0.06)] shrink-0 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-[3px] h-7 bg-[#F96702] rounded-full shrink-0" />
          <div>
            <h1 className="text-xl font-bold text-[#0A0A0A] tracking-tight">
              Knowledge Base
            </h1>
            <p className="text-sm text-[#6B7280] mt-0.5 font-normal">
              Approved answers used by RAG retrieval — embeddings are managed by
              the backend
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2.5">
          <div className="relative">
            <Search
              size={12}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-[#9CA3AF]"
            />
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="pl-8 pr-4 py-2 text-[11px] border border-[rgba(0,0,0,0.15)] rounded-full bg-white placeholder-[#B0B0B0] focus:outline-none focus:ring-2 focus:ring-[#F96702]/30 focus:border-[#F96702]/50 w-44 transition-all"
              placeholder="Search entries…"
            />
          </div>
          <button
            onClick={openCreate}
            className="flex items-center gap-1.5 px-5 py-2 text-[10px] bg-[#F96702] text-white rounded-full hover:bg-[#D95400] font-bold tracking-[0.06em] shadow-[0_2px_8px_rgba(249,103,2,0.3)] hover:shadow-[0_4px_16px_rgba(249,103,2,0.45)] transition-all"
          >
            <Plus size={12} /> Add Entry
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-auto px-8 py-6">
        {loading && (
          <div className="flex flex-col items-center justify-center gap-3 py-20 text-[#9CA3AF]">
            <Loader2 size={22} className="animate-spin text-[#F96702]" />
            <p className="text-xs font-medium">Loading knowledge base…</p>
          </div>
        )}
        {!loading && error && (
          <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-center gap-3">
            <AlertTriangle size={15} className="text-red-500 shrink-0" />
            <div className="flex-1">
              <p className="text-xs font-semibold text-red-800">
                Failed to load knowledge base
              </p>
              <p className="text-xs text-red-700 mt-0.5">
                Check that the backend is running on localhost:8080, then retry.
              </p>
            </div>
            <BtnSecondary onClick={load}>
              <RefreshCw size={11} /> Retry
            </BtnSecondary>
          </div>
        )}
        {!loading && !error && entries.length === 0 && (
          <div className="flex flex-col items-center justify-center gap-3 py-20 text-center">
            <div className="w-10 h-10 rounded-lg bg-[#FFF4EC] flex items-center justify-center">
              <BookOpen size={18} className="text-[#F96702]" />
            </div>
            <p className="text-xs font-semibold text-[#1F2937]">
              No knowledge entries yet
            </p>
            <p className="text-xs text-[#9CA3AF] max-w-xs">
              Add your first entry — approved entries are used to answer
              customer form questions automatically.
            </p>
            <BtnPrimary onClick={openCreate}>
              <Plus size={12} /> Add Entry
            </BtnPrimary>
          </div>
        )}
        {!loading && !error && entries.length > 0 && (
          <div className="bg-white rounded-xl border border-[rgba(0,0,0,0.06)] overflow-hidden">
            <table className="w-full">
              <thead>
                <tr className="bg-[#F7F8FA] border-b border-border">
                  {[
                    "Document / Section",
                    "Content",
                    "Department",
                    "Sharing",
                    "Approved",
                    "Last Updated",
                    "Actions",
                  ].map((h) => (
                    <th
                      key={h}
                      className="text-left px-4 py-2.5 text-[10px] font-bold text-[#6B7280] uppercase tracking-wide whitespace-nowrap"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {visible.length === 0 && (
                  <tr>
                    <td
                      colSpan={7}
                      className="px-4 py-6 text-xs text-[#9CA3AF] italic text-center"
                    >
                      No entries match “{query}”.
                    </td>
                  </tr>
                )}
                {visible.map((e) => (
                  <tr
                    key={e.id}
                    className="border-b border-border last:border-0 hover:bg-gray-50/50 transition-colors align-top"
                  >
                    <td className="px-4 py-2.5">
                      <p className="text-xs font-semibold text-[#1F2937]">
                        {e.documentTitle}
                      </p>
                      <p className="text-[10px] text-[#6B7280] mt-0.5">
                        {e.sectionTitle}
                      </p>
                    </td>
                    <td className="px-4 py-2.5 text-[11px] text-[#374151] max-w-[280px]">
                      <p className="line-clamp-2">{e.content}</p>
                    </td>
                    <td className="px-4 py-2.5 text-xs text-[#374151] whitespace-nowrap">
                      {e.department}
                    </td>
                    <td className="px-4 py-2.5">
                      <SharingPill status={e.sharingStatus} />
                    </td>
                    <td className="px-4 py-2.5">
                      {e.approved ? (
                        <span className="inline-flex items-center gap-1 text-xs text-green-600 font-medium whitespace-nowrap">
                          <CheckCircle size={11} /> Approved
                        </span>
                      ) : (
                        <span className="text-xs text-[#9CA3AF] whitespace-nowrap">
                          Draft
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-2.5 text-xs text-[#6B7280] whitespace-nowrap">
                      {fmtUpdated(e.lastUpdated)}
                    </td>
                    <td className="px-4 py-2.5">
                      <div className="flex gap-1.5">
                        <button
                          onClick={() => openEdit(e)}
                          className="flex items-center gap-1 px-3 py-1 text-[9px] font-bold border border-[rgba(0,0,0,0.15)] rounded-full text-[#6B7280] hover:border-[#F96702]/50 hover:text-[#F96702] tracking-[0.06em] uppercase transition-all"
                        >
                          <Edit3 size={9} /> Edit
                        </button>
                        <button
                          onClick={() => setDeleteTarget(e)}
                          className="flex items-center gap-1 px-3 py-1 text-[9px] font-bold border border-[#FCA5A5]/50 bg-[#FEF2F2] rounded-full text-[#991B1B] hover:bg-[#FEE2E2] tracking-[0.06em] uppercase transition-all"
                        >
                          <Trash2 size={9} /> Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Create / edit modal */}
      {formTarget !== null && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-xl p-5 w-[480px] max-h-[85vh] overflow-auto">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-[#1F2937]">
                {formTarget === "new" ? "Add Knowledge Entry" : "Edit Knowledge Entry"}
              </h3>
              <button
                onClick={() => setFormTarget(null)}
                className="text-gray-400 hover:text-gray-600"
              >
                <X size={14} />
              </button>
            </div>
            <div className="flex flex-col gap-2.5">
              <div className="grid grid-cols-2 gap-2.5">
                <div>
                  <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                    Document Title *
                  </label>
                  <input
                    className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs"
                    value={form.documentTitle}
                    onChange={(e) => setField("documentTitle", e.target.value)}
                  />
                </div>
                <div>
                  <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                    Section Title *
                  </label>
                  <input
                    className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs"
                    value={form.sectionTitle}
                    onChange={(e) => setField("sectionTitle", e.target.value)}
                  />
                </div>
              </div>
              <div>
                <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                  Content * — this text is embedded and searched
                </label>
                <textarea
                  rows={5}
                  className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs resize-y"
                  value={form.content}
                  onChange={(e) => setField("content", e.target.value)}
                />
              </div>
              <div>
                <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                  Source
                </label>
                <input
                  className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs"
                  placeholder="e.g. InfoSec Master Response Doc v3"
                  value={form.source}
                  onChange={(e) => setField("source", e.target.value)}
                />
              </div>
              <div className="grid grid-cols-2 gap-2.5">
                <div>
                  <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                    Department
                  </label>
                  <select
                    className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs bg-white"
                    value={form.department}
                    onChange={(e) => setField("department", e.target.value)}
                  >
                    {DEPARTMENT_OPTIONS.map((d) => (
                      <option key={d} value={d}>
                        {d}
                      </option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                    Sharing Status
                  </label>
                  <select
                    className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs bg-white"
                    value={form.sharingStatus}
                    onChange={(e) => setField("sharingStatus", e.target.value)}
                  >
                    {SHARING_OPTIONS.map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-2.5 items-end">
                <div>
                  <label className="text-[10px] font-medium text-[#6B7280] mb-1 block">
                    Last Updated (UTC)
                  </label>
                  <input
                    type="date"
                    className="w-full border border-border rounded-md px-2.5 py-1.5 text-xs"
                    value={form.lastUpdated ? form.lastUpdated.slice(0, 10) : ""}
                    onChange={(e) =>
                      setField(
                        "lastUpdated",
                        e.target.value ? `${e.target.value}T00:00:00` : null,
                      )
                    }
                  />
                </div>
                <label className="flex items-center gap-2 pb-1.5 cursor-pointer">
                  <input
                    type="checkbox"
                    className="accent-[#F96702]"
                    checked={form.approved}
                    onChange={(e) => setField("approved", e.target.checked)}
                  />
                  <span className="text-xs font-medium text-[#374151]">
                    Approved — used in retrieval
                  </span>
                </label>
              </div>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <BtnSecondary onClick={() => setFormTarget(null)}>
                Cancel
              </BtnSecondary>
              <BtnPrimary onClick={submitForm} disabled={saving}>
                {saving ? (
                  <>
                    <Loader2 size={11} className="animate-spin" /> Saving…
                  </>
                ) : formTarget === "new" ? (
                  "Create Entry"
                ) : (
                  "Save Changes"
                )}
              </BtnPrimary>
            </div>
          </div>
        </div>
      )}

      {/* Delete confirmation */}
      {deleteTarget && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-xl p-5 w-96">
            <h3 className="text-sm font-semibold text-[#1F2937] mb-1">
              Delete Knowledge Entry
            </h3>
            <p className="text-xs text-[#6B7280] mb-4">
              Delete <strong>{deleteTarget.documentTitle}</strong> /{" "}
              <strong>{deleteTarget.sectionTitle}</strong>? This removes it from
              retrieval and cannot be undone.
            </p>
            <div className="flex justify-end gap-2">
              <BtnSecondary onClick={() => setDeleteTarget(null)}>
                Cancel
              </BtnSecondary>
              <button
                onClick={confirmDelete}
                disabled={deleting}
                className={`flex items-center gap-1.5 px-5 py-2 text-[10px] font-bold rounded-full tracking-[0.06em] uppercase transition-all ${deleting ? "bg-[#E8E6E3] text-[#ABABAB] cursor-not-allowed" : "bg-[#DC2626] text-white hover:bg-[#B91C1C]"}`}
              >
                {deleting ? (
                  <>
                    <Loader2 size={11} className="animate-spin" /> Deleting…
                  </>
                ) : (
                  <>
                    <Trash2 size={11} /> Delete
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
